### ISSUE TITLE
Definition - Check the certificates generated for the GUI and BSS

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-tests#227]
The goal of this tests is verify that the certificate generated for GUI and BSS are valid and placed in the right way

**Comment by pkarkazis** [comment]
During this test, a validation of the ssl certificates will be performed. The validation procedure consisting of the following actions:
1) check that the certificate exists on server
2) check expiration date
3) get cert serial number
4) get Issuer

**Comment by srodriguezOPT** [comment]
get cert serial number
openssl x509 -in sonata.crt -serial -noout

check expiration date
openssl x509 -noout -in sonata.crt -dates

openssl get Issuer
openssl x509 -noout -in sonata.crt -issuer

The following two commands will print out md5 sums of the certificate and key. These sums can be compared to verify that the certificate and key match.

openssl x509 -noout -modulus -in sonata.crt | openssl md5
openssl rsa -noout -modulus -in sonata.key| openssl md5
