### ISSUE TITLE
Definition - Stress monitoring

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-tests#232]
Stress the monitoring system. Try to get numbers about how many metrics per second can support. Metrics lost, response time.

**Comment by pkarkazis** [comment]
Monitoring stress test is going to check system's performance in three objectives:
1) Monitoring manager API behaviour under heavy load  
2) Maximum number of metrics posted from probes to system
4) Maximum number of notification alerts to Son-Broker (optional)
