### ISSUE TITLE
Postgres database insert error

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-tests#249]
There is an issue adding the VIM in the database. It marked as fail the job int-9-environment-deploy. It is happening after [son-sp-infrabstract PR#63]( https://github.com/sonata-nfv/son-sp-infrabstract/pull/63)

ERROR:  column "tenant" of relation "vim" does not exist LINE 1: ...INTO VIM (uuid, type, vendor, endpoint, username, tenant, te...^ Build step 'Execute shell' marked build as failure

**Comment by DarioValocchi** [comment]
I will look into it. Infra Repo structure has changed after VNF placement requirement.

**Comment by DarioValocchi** [comment]
Although there must be a misconfiguration of int-9, because it shouldn't take an IA version that did not passet the development tests.

**Comment by felipevicens** [comment]
@DarioValocchi I think the issue is in the son-sp-infrabstract-vim. It pushed the container when the test failed. I will have a look into it. https://jenkins.sonata-nfv.eu/job/son-sp-infrabstract-vim/227/console

**Comment by DarioValocchi** [comment]
Sounds possible. When the currend PR will be accepted we will need to change int-9 anyway to push the right VIM configurations to the DB, respecting the new table structure.

**Comment by felipevicens** [comment]
It is fixed. Database model was changed, The tests were adapted
